### ISSUE TITLE
babylon to startdict files convertor

### ISSUE THREAD

**Issue by chandrasekharanr** [indic-dict/stardict-test#1]
It will be useful if you can check in the code to convert .babylon to stardict format files 
(1) . somedict.ifo
(2) . somedict.idx or somedict.idx.gz
(3) . somedict.dict or somedict.dict.dz
(4) . somedict.syn (optional)

If is already there, please point me to it?

Thanks!

**Comment by vvasuki** [comment]
We (and wrappers such as https://github.com/indic-dict/dict-tools/blob/master/bin/bash/full_build.sh and https://github.com/indic-dict/dict-tools/blob/master/bin/bash/tsv_to_stardict.sh ) use stardict-tools package on ubuntu linux, which provides the babylon or stardict-babylon binary. Also take a look at what https://github.com/indic-dict/stardict-sanskrit/blob/master/.travis.yml does.

**Comment by drdhaval2785** [comment]
If you use ubuntu / similar linux distribution,
you can do
```
sudo apt install stardict-tools
stardict-editor
```
This will open a stardict editor.
Select the .babylon file.
Choose babylon format in the drop down.
Click compile.

**Comment by chandrasekharanr** [comment]
Ok, Thanks! Would it possible to generate both the babylon and stardict-babylon binaries going forward? For example, we have only the babylon binaries here :  https://github.com/indic-dict/stardict-tamil/tree/master/ta-head

**Comment by vvasuki** [comment]
> Would it possible to generate both the babylon and stardict-babylon binaries going forward? For example, we have only the babylon binaries here : https://github.com/indic-dict/stardict-tamil/tree/master/ta-head

Check the gh-pages branch
